// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package approval

import (
	"errors"
	"fmt"
)

const (
	// StepStatusPending is a StepStatus of type Pending.
	StepStatusPending StepStatus = "Pending"
	// StepStatusApproved is a StepStatus of type Approved.
	StepStatusApproved StepStatus = "Approved"
	// StepStatusRejected is a StepStatus of type Rejected.
	StepStatusRejected StepStatus = "Rejected"
)

var ErrInvalidStepStatus = errors.New("not a valid StepStatus")

// StepStatusValues returns a list of the values for StepStatus
func StepStatusValues() []StepStatus {
	return []StepStatus{
		StepStatusPending,
		StepStatusApproved,
		StepStatusRejected,
	}
}

// String implements the Stringer interface.
func (x StepStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x StepStatus) IsValid() bool {
	_, err := ParseStepStatus(string(x))
	return err == nil
}

var _StepStatusValue = map[string]StepStatus{
	"Pending":  StepStatusPending,
	"Approved": StepStatusApproved,
	"Rejected": StepStatusRejected,
}

// ParseStepStatus attempts to convert a string to a StepStatus.
func ParseStepStatus(name string) (StepStatus, error) {
	if x, ok := _StepStatusValue[name]; ok {
		return x, nil
	}
	return StepStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidStepStatus)
}

// MarshalText implements the text marshaller method.
func (x StepStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *StepStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseStepStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *StepStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
