// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package user

import (
	"errors"
	"fmt"
)

const (
	// RoleEmployee is a Role of type employee.
	RoleEmployee Role = "employee"
	// RoleManager is a Role of type manager.
	RoleManager Role = "manager"
	// RoleFinance is a Role of type finance.
	RoleFinance Role = "finance"
)

var ErrInvalidRole = errors.New("not a valid Role")

// RoleValues returns a list of the values for Role
func RoleValues() []Role {
	return []Role{
		RoleEmployee,
		RoleManager,
		RoleFinance,
	}
}

// String implements the Stringer interface.
func (x Role) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Role) IsValid() bool {
	_, err := ParseRole(string(x))
	return err == nil
}

var _RoleValue = map[string]Role{
	"employee": RoleEmployee,
	"manager":  RoleManager,
	"finance":  RoleFinance,
}

// ParseRole attempts to convert a string to a Role.
func ParseRole(name string) (Role, error) {
	if x, ok := _RoleValue[name]; ok {
		return x, nil
	}
	return Role(""), fmt.Errorf("%s is %w", name, ErrInvalidRole)
}

// MarshalText implements the text marshaller method.
func (x Role) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Role) UnmarshalText(text []byte) error {
	tmp, err := ParseRole(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Role) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
