// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// EventTypeCreated is a EventType of type created.
	EventTypeCreated EventType = "created"
	// EventTypeSubmitted is a EventType of type submitted.
	EventTypeSubmitted EventType = "submitted"
	// EventTypeStepApproved is a EventType of type stepApproved.
	EventTypeStepApproved EventType = "stepApproved"
	// EventTypeApproved is a EventType of type approved.
	EventTypeApproved EventType = "approved"
	// EventTypeRejected is a EventType of type rejected.
	EventTypeRejected EventType = "rejected"
)

var ErrInvalidEventType = errors.New("not a valid EventType")

// EventTypeValues returns a list of the values for EventType
func EventTypeValues() []EventType {
	return []EventType{
		EventTypeCreated,
		EventTypeSubmitted,
		EventTypeStepApproved,
		EventTypeApproved,
		EventTypeRejected,
	}
}

// String implements the Stringer interface.
func (x EventType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventType) IsValid() bool {
	_, err := ParseEventType(string(x))
	return err == nil
}

var _EventTypeValue = map[string]EventType{
	"created":      EventTypeCreated,
	"submitted":    EventTypeSubmitted,
	"stepApproved": EventTypeStepApproved,
	"approved":     EventTypeApproved,
	"rejected":     EventTypeRejected,
}

// ParseEventType attempts to convert a string to a EventType.
func ParseEventType(name string) (EventType, error) {
	if x, ok := _EventTypeValue[name]; ok {
		return x, nil
	}
	return EventType(""), fmt.Errorf("%s is %w", name, ErrInvalidEventType)
}

// MarshalText implements the text marshaller method.
func (x EventType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EventType) UnmarshalText(text []byte) error {
	tmp, err := ParseEventType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *EventType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
