// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"errors"
	"fmt"
)

const (
	// StatusDraft is a Status of type Draft.
	StatusDraft Status = "Draft"
	// StatusSubmitted is a Status of type Submitted.
	StatusSubmitted Status = "Submitted"
	// StatusApproved is a Status of type Approved.
	StatusApproved Status = "Approved"
	// StatusRejected is a Status of type Rejected.
	StatusRejected Status = "Rejected"
)

var ErrInvalidStatus = errors.New("not a valid Status")

// StatusValues returns a list of the values for Status
func StatusValues() []Status {
	return []Status{
		StatusDraft,
		StatusSubmitted,
		StatusApproved,
		StatusRejected,
	}
}

// String implements the Stringer interface.
func (x Status) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Status) IsValid() bool {
	_, err := ParseStatus(string(x))
	return err == nil
}

var _StatusValue = map[string]Status{
	"Draft":     StatusDraft,
	"Submitted": StatusSubmitted,
	"Approved":  StatusApproved,
	"Rejected":  StatusRejected,
}

// ParseStatus attempts to convert a string to a Status.
func ParseStatus(name string) (Status, error) {
	if x, ok := _StatusValue[name]; ok {
		return x, nil
	}
	return Status(""), fmt.Errorf("%s is %w", name, ErrInvalidStatus)
}

// MarshalText implements the text marshaller method.
func (x Status) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Status) UnmarshalText(text []byte) error {
	tmp, err := ParseStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Status) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// TypeTravel is a Type of type Travel.
	TypeTravel Type = "Travel"
	// TypeSoftware is a Type of type Software.
	TypeSoftware Type = "Software"
	// TypeEquipment is a Type of type Equipment.
	TypeEquipment Type = "Equipment"
	// TypeMeal is a Type of type Meal.
	TypeMeal Type = "Meal"
	// TypeOther is a Type of type Other.
	TypeOther Type = "Other"
)

var ErrInvalidType = errors.New("not a valid Type")

// TypeValues returns a list of the values for Type
func TypeValues() []Type {
	return []Type{
		TypeTravel,
		TypeSoftware,
		TypeEquipment,
		TypeMeal,
		TypeOther,
	}
}

// String implements the Stringer interface.
func (x Type) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Type) IsValid() bool {
	_, err := ParseType(string(x))
	return err == nil
}

var _TypeValue = map[string]Type{
	"Travel":    TypeTravel,
	"Software":  TypeSoftware,
	"Equipment": TypeEquipment,
	"Meal":      TypeMeal,
	"Other":     TypeOther,
}

// ParseType attempts to convert a string to a Type.
func ParseType(name string) (Type, error) {
	if x, ok := _TypeValue[name]; ok {
		return x, nil
	}
	return Type(""), fmt.Errorf("%s is %w", name, ErrInvalidType)
}

// MarshalText implements the text marshaller method.
func (x Type) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Type) UnmarshalText(text []byte) error {
	tmp, err := ParseType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Type) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
